### ISSUE TITLE
NULL on Windows?

### ISSUE THREAD

**Issue by vspinu** [eddelbuettel/gettz#4]
I am getting NULL out of gettz() on windows 10 with R-devel. Is this intended to work with windows?

Thanks!

**Comment by eddelbuettel** [comment]
From the top of my head, I believe this to be a regression.   What does R-release do?

The package came to be because on Linux it wasn't always ensure the proper softlink were set / R looked in the wrong place.  That since got rectified in R itself (should have pushed for that patch ...).  And as I recally, on Windoze we were always set.

**Comment by eddelbuettel** [comment]
My memory appears to be faulty.  `NULL` may be a feature.  See [the source](https://github.com/eddelbuettel/gettz/blob/master/src/gettz.cpp).

**Comment by eddelbuettel** [comment]
From [DESCRIPTION](https://github.com/eddelbuettel/gettz/blob/master/DESCRIPTION)

> Description: A function to retrieve the system timezone on Unix systems
 which has been found to find an answer when 'Sys.timezone()' has failed.
 It is based on an answer by Duane McCully posted on 'StackOverflow', and
 adapted to be callable from R. The package also builds on Windows, but
 just returns NULL.

**Comment by eddelbuettel** [comment]
That said, I you have the energy and knowledge to chase this from the windows registry: a PR would be most welcome.

**Comment by vspinu** [comment]
Thanks. I am not windows user, nor I am wiling to go far for this feature. I will just call R's Sys.timezone() from C and be done with it. R goes through quite [some pain](https://github.com/SurajGupta/r-source/blob/master/src/extra/tzone/registryTZ.c) to get it right on windows, so any patch will probably end up doing something similar.

**Comment by eddelbuettel** [comment]
Yes.  My problem was that in certain cases on Linux that very call would not work.  R failed.  Hence gettz.

On Windows, it mostly does the right thing so gettz does not really need to help there.
